GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '1Q2w3e4r5t6y7' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY '1Q2w3e4r5t6y7';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%';
FLUSH PRIVILEGES;
