- name: Desplegar stack Inception 42 Barelona
  hosts: all
  become: yes
  vars_files:
    - vars.yml
    - paths.yml  
  tasks:

    - name: Copiar keys deploy al host
      copy:
        src: "{{ keys_tar }}"
        dest: "{{ keys_tar }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"

    - name: Descomprimir keys.tar.gz
      unarchive:
        src: "{{ keys_tar }}"
        dest: "{{ home_dir }}"
        remote_src: yes
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Mover deploy key al .ssh
      command: mv "{{ home_dir }}/keys/deploy_key_cloud" "{{ ssh_dir }}/deploy_key_cloud"
      args:
        removes: "{{ home_dir }}/keys/deploy_key_cloud"

    - name: Cambiar propietario y permisos de la clave privada
      file:
        path: "{{ ssh_dir }}/deploy_key_cloud"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'

    - name: Add GitHub to known_hosts
      known_hosts:
        path: "{{ ssh_dir }}/known_hosts"
        name: github.com
        key: "{{ lookup('pipe','ssh-keyscan github.com') }}"
        state: present

    - name: Set correct permissions on known_hosts
      file:
        path: "{{ ssh_dir }}/known_hosts"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Configure SSH to use deploy key for GitHub
      copy:
        dest: "{{ ssh_dir }}/config"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
        content: |
          Host github.com
              HostName github.com
              User git
              IdentityFile "{{ ssh_dir }}/deploy_key_cloud"
              IdentitiesOnly yes

    - name: Test SSH connection to GitHub
      become_user: "{{ user_name }}"
      command: ssh -T git@github.com
      register: github_test
      failed_when: "'successfully authenticated' not in github_test.stderr" # solo muestra si es err

    - name: Show GitHub SSH test result
      debug:
        var: github_test.stdout

    - name: Clonar repositorio Cloud-1
      git:
        repo: 'git@github.com:nach131/Cloud-1.git'
        dest: "{{ cloud_dir }}/"
        version: main
        force: yes            # fuerza actualizaci칩n si ya existe
        update: yes           # actualiza si ya est치 clonado
      become_user: "{{ user_name }}"

    - name: Generar fichero .env desde plantilla
      template:
        src: env.j2
        dest: "{{ cloud_dir }}/.env"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0600"

    - name: Copiar data.tar.gz al host
      copy:
        src: "{{ data_tar }}"
        dest: "{{ data_tar }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"

    - name: Descomprimir data.tar.gz
      unarchive:
        src: "{{ data_tar }}"
        dest: "{{ cloud_dir }}"
        remote_src: yes
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copiar docker_images_backup.tar.gz al host
      copy:
        src: "{{ docker_backup }}"
        dest: "{{ docker_backup }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"

    - name: Cargar im치genes de Docker desde el backup
      become_user: "{{ user_name }}"
      shell: "docker load -i {{ docker_backup }}"

    - name: Levantar servicios con docker-compose
      become_user: "{{ user_name }}"
      shell: docker compose up -d
      args:
        chdir: "{{ cloud_dir }}"

    # - name: Levantar servicios con docker-compose v2
    #   community.docker.docker_compose_v2:
    #     project_src: "{{ cloud_dir }}"
    #     state: present
    #     build: no       # hacer build de im치genes, cambia a yes
    #     # restarted: yes  # opcional, reinicia contenedores si cambian
    #   become_user: "{{ user_name }}"

#  ====================================================================================

# ansible-playbook -i hosts-control deploy_stack.yml --ask-become-pass --ask-vault-pass

# ansible-playbook -i hosts-control deploy_stack.yml -l cloud2 --ask-become-pass --ask-vault-pass
