- name: Desplegar stack Inception 42 Barelona
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:

        # 11 - Copiar keys
    - name: Copiar keys deploy al host
      copy:
        src: /home/nacho/keys.tar.gz
        # src: "{{ local_data_path }}/data.tar.gz"
        dest: "/home/nacho/keys.tar.gz"
        owner: nacho
        group: nacho
        mode: "0644"

    - name: Descomprimir keys.tar.gz
      unarchive:
        src: /home/nacho/keys.tar.gz
        dest: /home/nacho
        remote_src: yes
        owner: nacho
        group: nacho

    - name: Mover deploy key al .ssh
      command: mv /home/nacho/keys/deploy_key_cloud /home/nacho/.ssh/deploy_key_cloud
      args:
        removes: /home/nacho/keys/deploy_key_cloud

    - name: Cambiar propietario y permisos de la clave privada
      file:
        path: /home/nacho/.ssh/deploy_key_cloud
        owner: nacho
        group: nacho
        mode: '0600'

    - name: Add GitHub to known_hosts
      known_hosts:
        path: /home/nacho/.ssh/known_hosts
        name: github.com
        key: "{{ lookup('pipe','ssh-keyscan github.com') }}"
        state: present

    - name: Set correct permissions on known_hosts
      file:
        path: /home/nacho/.ssh/known_hosts
        owner: nacho
        group: nacho
        mode: '0644'

    - name: Configure SSH to use deploy key for GitHub
      copy:
        dest: /home/nacho/.ssh/config
        owner: nacho
        group: nacho
        mode: '0600'
        content: |
          Host github.com
              HostName github.com
              User git
              IdentityFile /home/nacho/.ssh/deploy_key_cloud
              IdentitiesOnly yes

    - name: Test SSH connection to GitHub
      become_user: nacho
      command: ssh -T git@github.com
      register: github_test
      failed_when: "'successfully authenticated' not in github_test.stderr" # solo muestra si es err

    - name: Show GitHub SSH test result
      debug:
        var: github_test.stdout

    # 12 - Clonar repo
    - name: Clonar repositorio Cloud-1
      git:
        repo: 'git@github.com:nach131/Cloud-1.git'
        dest: /home/nacho/Cloud-1/
        version: main
        force: yes            # fuerza actualización si ya existe
        update: yes           # actualiza si ya está clonado
      become_user: nacho

    - name: Generar fichero .env desde plantilla
      template:
        src: env.j2
        dest: "/home/nacho/Cloud-1/.env"
        owner: nacho
        group: nacho
        mode: "0600"

      # 11 - Copiar Datos 
    - name: Copiar data.tar.gz al host
      copy:
        src: /home/nacho/data.tar.gz
        # src: "{{ local_data_path }}/data.tar.gz"
        dest: "/home/nacho/Cloud-1/data.tar.gz"
        owner: nacho
        group: nacho
        mode: "0644"

    - name: Descomprimir data.tar.gz
      unarchive:
        src: /home/nacho/Cloud-1/data.tar.gz
        dest: /home/nacho/Cloud-1
        remote_src: yes
        owner: nacho
        group: nacho

    - name: Copiar docker_images_backup.tar.gz al host
      copy:
        src: /home/nacho/docker_images_backup.tar.gz
        dest: /home/nacho/docker_images_backup.tar.gz
        owner: nacho
        group: nacho
        mode: "0644"

    - name: Cargar imágenes de Docker desde el backup
      become_user: nacho
      shell: docker load -i /home/nacho/docker_images_backup.tar.gz

    - name: Levantar servicios con docker-compose
      become_user: nacho
      shell: docker compose up -d
      args:
        chdir: "/home/nacho/Cloud-1"

# ansible-playbook -i hosts-control deploy_stack.yml --ask-become-pass --ask-vault-pass

# ansible-playbook -i hosts-control deploy_stack.yml -l cloud2 --ask-become-pass --ask-vault-pass
