- name: Desplegar stack Inception 42 Barelona
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:

    # 1 — Uninstall old versions
    - name: Remove old Docker packages
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: yes

    # 2 — apt update
    - name: Update apt cache
      apt:
        update_cache: yes

    # 3 — Install dependencies
    - name: Install ca-certificates and curl
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    # 4 — Create keyrings directory
    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # 5 — Download Docker GPG key
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    # 6 — Add Docker repo using the new .sources format
    - name: Add Docker apt repository in .sources format
      copy:
        dest: /etc/apt/sources.list.d/docker.sources
        mode: '0644'
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_facts['lsb']['codename'] }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc

    # 7 — apt update again
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    # 8 — Install Docker packages
    - name: Install Docker Engine packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

      # 9 — Ensure docker group exists
    - name: Ensure docker group exists
      group:
        name: docker
        state: present
        
    - name: Add user nacho to docker group
      user:
        name: "nacho"
        groups: docker
        append: yes


    # # 10 — Ensure Docker service is running
    # - name: Ensure Docker is running
    #   systemd:
    #     name: docker
    #     state: started
    #     enabled: yes

    # # 11 — Check Docker status
    # - name: Check Docker service status
    #   command: systemctl is-active docker
    #   register: docker_status
    #   changed_when: false

    # - name: Show Docker status
    #   debug:
    #     msg: "Docker status: {{ docker_status.stdout }}"



# ansible-playbook -i hosts-control deploy_stack.yml --ask-become-pass --ask-vault-pass

# ansible-playbook -i hosts-control deploy_stack.yml -l cloud2 --ask-become-pass --ask-vault-pass
